use_frameworks!

target 'NorthLayout-ios' do
    platform :ios, '8.0'
    link_with 'NorthLayout-ios', 'NorthLayout-ios-Tests'
    pod 'NorthLayout', :path => '../'
end

target 'NorthLayout-osx' do
    platform :osx, '10.10'
    link_with 'NorthLayout-osx', 'NorthLayout-osx-Tests'
    pod 'NorthLayout', :path => '../'
end

