use_frameworks!

target 'NorthLayout-ios' do
  platform :ios, '9.0'
  pod 'NorthLayout', :path => '../'
  pod 'FootlessParser', git: 'https://github.com/banjun/FootlessParser', branch: 'banjun'

  target 'NorthLayout-ios-Tests' do
    inherit! :search_paths
  end
end

target 'NorthLayout-osx' do
  platform :osx, '10.11'
  pod 'NorthLayout', :path => '../'
end

